### ISSUE TITLE
Compilation error: 

### ISSUE THREAD

**Issue by smoochiee** [miki232/Esp32-BleSpam#1]
Compilation error: no matching function for call to 'BLEDevice::init(String)'

**Comment by miki232** [comment]
Which version of ArduinoIDE do you have?
You can try to add this in the "Additional boards manager URLs"
https://dl.espressif.com/dl/package_esp32_index.json,https://espressif.github.io/arduino-esp32/package_esp32_index.json,https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_dev_index.json

**Comment by smoochiee** [comment]
i use version 2.2.1





C:\Users\Dell\AppData\Local\Temp\.arduinoIDE-unsaved20231116-19380-5vdyhj.ynh0a\sketch_dec16a\sketch_dec16a.ino: In function 'void setup()':
C:\Users\Dell\AppData\Local\Temp\.arduinoIDE-unsaved20231116-19380-5vdyhj.ynh0a\sketch_dec16a\sketch_dec16a.ino:585:31: error: no matching function for call to 'BLEDevice::init(String)'
   BLEDevice::init(String(name));
                               ^
In file included from C:\Users\Dell\AppData\Local\Temp\.arduinoIDE-unsaved20231116-19380-5vdyhj.ynh0a\sketch_dec16a\sketch_dec16a.ino:7:
C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE\src/BLEDevice.h:39:21: note: candidate: 'static void BLEDevice::init(std::__cxx11::string)'
  static void        init(std::string deviceName);   // Initialize the local BLE environment.
                     ^~~~
C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE\src/BLEDevice.h:39:21: note:   no known conversion for argument 1 from 'String' to 'std::__cxx11::string' {aka 'std::__cxx11::basic_string<char>'}
C:\Users\Dell\AppData\Local\Temp\.arduinoIDE-unsaved20231116-19380-5vdyhj.ynh0a\sketch_dec16a\sketch_dec16a.ino:620:69: error: no matching function for call to 'BLEAdvertisementData::addData(String)'
     oAdvertisementData.addData(String((char*)packet, sizeof(packet)));
                                                                     ^
In file included from C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE\src/BLEServer.h:19,
                 from C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE\src/BLEDevice.h:18,
                 from C:\Users\Dell\AppData\Local\Temp\.arduinoIDE-unsaved20231116-19380-5vdyhj.ynh0a\sketch_dec16a\sketch_dec16a.ino:7:
C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE\src/BLEAdvertising.h:33:7: note: candidate: 'void BLEAdvertisementData::addData(std::__cxx11::string)'
  void addData(std::string data);         // Add data to the payload.
       ^~~~~~~
C:\Users\Dell\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.11\libraries\BLE\src/BLEAdvertising.h:33:7: note:   no known conversion for argument 1 from 'String' to 'std::__cxx11::string' {aka 'std::__cxx11::basic_string<char>'}

exit status 1

Compilation error: no matching function for call to 'BLEDevice::init(String)'

**Comment by smoochiee** [comment]
version 2.2.1..already fix..ty
